import { TractorBookingStatus, TractorRateType } from "@prisma/client";
import { z } from "zod";

// Mirrors the TractorBookingStatus enum in schema.prisma — used for
// query-param filtering.
const TRACTOR_BOOKING_STATUSES = Object.values(TractorBookingStatus) as [
  TractorBookingStatus,
  ...TractorBookingStatus[]
];

const TRACTOR_RATE_TYPES = Object.values(TractorRateType) as [
  TractorRateType,
  ...TractorRateType[]
];

// cuid() ids as generated by Prisma's @default(cuid()) — same shape as
// every other id in this codebase.
const tractorOwnerIdField = z
  .string({ required_error: "tractorOwnerId is required" })
  .trim()
  .min(1, "tractorOwnerId is required");

const workTypeField = z
  .string({ required_error: "workType is required" })
  .trim()
  .min(2, "workType must be at least 2 characters")
  .max(100, "workType must be at most 100 characters");

// Accepts any string Date() can parse (ISO date or datetime), then
// normalizes to a real Date. Past dates are rejected — a farmer can book
// for today or a future date, not a date that has already passed. Mirrors
// workDateField in workRequest.validator.ts.
const bookingDateField = z
  .string({ required_error: "bookingDate is required" })
  .trim()
  .refine((value) => !Number.isNaN(new Date(value).getTime()), {
    message: "bookingDate must be a valid date",
  })
  .transform((value) => new Date(value))
  .refine(
    (date) => {
      const startOfToday = new Date();
      startOfToday.setHours(0, 0, 0, 0);
      return date.getTime() >= startOfToday.getTime();
    },
    { message: "bookingDate cannot be in the past" }
  );

const locationField = z
  .string({ required_error: "location is required" })
  .trim()
  .min(5, "location must be at least 5 characters")
  .max(500, "location must be at most 500 characters");

const rateTypeField = z.enum(TRACTOR_RATE_TYPES, {
  required_error: "rateType is required",
  invalid_type_error: `rateType must be one of: ${TRACTOR_RATE_TYPES.join(", ")}`,
});

const rateField = z
  .number({ required_error: "rate is required", invalid_type_error: "rate must be a number" })
  .positive("rate must be greater than 0")
  .max(100000, "rate must be at most 100000");

const messageField = z
  .string()
  .trim()
  .max(500, "message must be at most 500 characters")
  .optional();

export const createTractorBookingSchema = z.object({
  tractorOwnerId: tractorOwnerIdField,
  workType: workTypeField,
  bookingDate: bookingDateField,
  location: locationField,
  rateType: rateTypeField,
  rate: rateField,
  message: messageField,
});

export type CreateTractorBookingInput = z.infer<typeof createTractorBookingSchema>;

// The tractor owner's response to a PENDING booking. Kept as a single
// endpoint with an `action` discriminator, mirrors respondWorkRequestSchema.
export const respondTractorBookingSchema = z.object({
  action: z.enum(["ACCEPT", "REJECT"], {
    required_error: "action is required",
    invalid_type_error: "action must be either ACCEPT or REJECT",
  }),
});

export type RespondTractorBookingInput = z.infer<typeof respondTractorBookingSchema>;

// Shared list query for both the farmer's "sent" view and the tractor
// owner's "received" view — which side is being listed is determined by
// the caller's role in the controller, not by this schema.
export const listTractorBookingsQuerySchema = z.object({
  status: z.enum(TRACTOR_BOOKING_STATUSES).optional(),
  page: z.coerce.number().int().positive().optional().default(1),
  limit: z.coerce.number().int().positive().max(50).optional().default(20),
});

export type ListTractorBookingsQuery = z.infer<typeof listTractorBookingsQuerySchema>;
