import { TransportBookingStatus, TransportRateType } from "@prisma/client";
import { z } from "zod";

// Mirrors the TransportBookingStatus enum in schema.prisma — used for
// query-param filtering.
const TRANSPORT_BOOKING_STATUSES = Object.values(TransportBookingStatus) as [
  TransportBookingStatus,
  ...TransportBookingStatus[]
];

const TRANSPORT_RATE_TYPES = Object.values(TransportRateType) as [
  TransportRateType,
  ...TransportRateType[]
];

// cuid() ids as generated by Prisma's @default(cuid()) — same shape as
// every other id in this codebase.
const transportProviderIdField = z
  .string({ required_error: "transportProviderId is required" })
  .trim()
  .min(1, "transportProviderId is required");

const goodsTypeField = z
  .string({ required_error: "goodsType is required" })
  .trim()
  .min(2, "goodsType must be at least 2 characters")
  .max(100, "goodsType must be at most 100 characters");

// Accepts any string Date() can parse (ISO date or datetime), then
// normalizes to a real Date. Past dates are rejected — a farmer can book
// for today or a future date, not a date that has already passed. Mirrors
// bookingDateField in tractorBooking.validator.ts.
const bookingDateField = z
  .string({ required_error: "bookingDate is required" })
  .trim()
  .refine((value) => !Number.isNaN(new Date(value).getTime()), {
    message: "bookingDate must be a valid date",
  })
  .transform((value) => new Date(value))
  .refine(
    (date) => {
      const startOfToday = new Date();
      startOfToday.setHours(0, 0, 0, 0);
      return date.getTime() >= startOfToday.getTime();
    },
    { message: "bookingDate cannot be in the past" }
  );

const locationField = (label: string) =>
  z
    .string({ required_error: `${label} is required` })
    .trim()
    .min(5, `${label} must be at least 5 characters`)
    .max(500, `${label} must be at most 500 characters`);

const rateTypeField = z.enum(TRANSPORT_RATE_TYPES, {
  required_error: "rateType is required",
  invalid_type_error: `rateType must be one of: ${TRANSPORT_RATE_TYPES.join(", ")}`,
});

const rateField = z
  .number({ required_error: "rate is required", invalid_type_error: "rate must be a number" })
  .positive("rate must be greater than 0")
  .max(100000, "rate must be at most 100000");

const messageField = z
  .string()
  .trim()
  .max(500, "message must be at most 500 characters")
  .optional();

export const createTransportBookingSchema = z.object({
  transportProviderId: transportProviderIdField,
  goodsType: goodsTypeField,
  pickupLocation: locationField("pickupLocation"),
  dropLocation: locationField("dropLocation"),
  bookingDate: bookingDateField,
  rateType: rateTypeField,
  rate: rateField,
  message: messageField,
});

export type CreateTransportBookingInput = z.infer<typeof createTransportBookingSchema>;

// The transport provider's response to a PENDING booking. Kept as a single
// endpoint with an `action` discriminator, mirrors respondTractorBookingSchema.
export const respondTransportBookingSchema = z.object({
  action: z.enum(["ACCEPT", "REJECT"], {
    required_error: "action is required",
    invalid_type_error: "action must be either ACCEPT or REJECT",
  }),
});

export type RespondTransportBookingInput = z.infer<typeof respondTransportBookingSchema>;

// Shared list query for both the farmer's "sent" view and the transport
// provider's "received" view — which side is being listed is determined by
// the caller's role in the controller, not by this schema.
export const listTransportBookingsQuerySchema = z.object({
  status: z.enum(TRANSPORT_BOOKING_STATUSES).optional(),
  page: z.coerce.number().int().positive().optional().default(1),
  limit: z.coerce.number().int().positive().max(50).optional().default(20),
});

export type ListTransportBookingsQuery = z.infer<typeof listTransportBookingsQuerySchema>;
