import { OfferStatus } from "@prisma/client";
import { z } from "zod";

// Mirrors the OfferStatus enum in schema.prisma — used for query-param
// filtering.
const OFFER_STATUSES = Object.values(OfferStatus) as [OfferStatus, ...OfferStatus[]];

// cuid() ids as generated by Prisma's @default(cuid()) — same shape as
// every other id in this codebase.
const listingIdField = z
  .string({ required_error: "listingId is required" })
  .trim()
  .min(1, "listingId is required");

// Mirrors priceField in produce.validator.ts — an offer's price is on the
// same scale as a listing's price, so it shares the same bounds.
const offerPriceField = z
  .number({
    required_error: "offerPrice is required",
    invalid_type_error: "offerPrice must be a number",
  })
  .positive("offerPrice must be greater than 0")
  .max(10_000_000, "offerPrice must be at most 10,000,000");

// Mirrors quantityField in produce.validator.ts. The additional rule that
// this cannot exceed the listing's own available quantity is enforced in
// produceOffer.service.ts, not here, since it depends on the listing being
// offered against.
const quantityField = z
  .number({
    required_error: "quantity is required",
    invalid_type_error: "quantity must be a number",
  })
  .positive("quantity must be greater than 0")
  .max(1_000_000, "quantity must be at most 1,000,000");

// Mirrors messageField in transportBooking.validator.ts / tractorBooking.validator.ts.
const messageField = z
  .string()
  .trim()
  .max(500, "message must be at most 500 characters")
  .optional();

export const createProduceOfferSchema = z.object({
  listingId: listingIdField,
  offerPrice: offerPriceField,
  quantity: quantityField,
  message: messageField,
});

export type CreateProduceOfferInput = z.infer<typeof createProduceOfferSchema>;

// The farmer's response to a PENDING offer. Kept as a single endpoint with
// an `action` discriminator, mirrors respondTransportBookingSchema.
export const respondProduceOfferSchema = z.object({
  action: z.enum(["ACCEPT", "REJECT"], {
    required_error: "action is required",
    invalid_type_error: "action must be either ACCEPT or REJECT",
  }),
});

export type RespondProduceOfferInput = z.infer<typeof respondProduceOfferSchema>;

// Shared list query for both the buyer's "sent" view and the farmer's
// "received" view — which side is being listed is determined by the
// caller's role in the controller, not by this schema. listingId lets a
// farmer narrow to the offers on one specific listing (e.g. from that
// listing's "View offers" link).
export const listProduceOffersQuerySchema = z.object({
  status: z.enum(OFFER_STATUSES).optional(),
  listingId: z.string().trim().min(1).optional(),
  page: z.coerce.number().int().positive().optional().default(1),
  limit: z.coerce.number().int().positive().max(50).optional().default(20),
});

export type ListProduceOffersQuery = z.infer<typeof listProduceOffersQuerySchema>;
