import { WorkRequestStatus } from "@prisma/client";
import { z } from "zod";

// Mirrors the WorkRequestStatus enum in schema.prisma — used both for
// query-param filtering and the accept/reject action below.
const WORK_REQUEST_STATUSES = Object.values(WorkRequestStatus) as [
  WorkRequestStatus,
  ...WorkRequestStatus[]
];

// cuid() ids as generated by Prisma's @default(cuid()) — same shape as
// every other id in this codebase (User.id, LabourProfile.id, ...).
const labourIdField = z
  .string({ required_error: "labourId is required" })
  .trim()
  .min(1, "labourId is required");

const workTypeField = z
  .string({ required_error: "workType is required" })
  .trim()
  .min(2, "workType must be at least 2 characters")
  .max(100, "workType must be at most 100 characters");

// Accepts any string Date() can parse (ISO date or datetime), then
// normalizes to a real Date so the service layer never has to re-parse.
// Past dates are rejected here (compared to the start of today) — a
// farmer can request work for today or a future date, not a date that has
// already passed.
const workDateField = z
  .string({ required_error: "workDate is required" })
  .trim()
  .refine((value) => !Number.isNaN(new Date(value).getTime()), {
    message: "workDate must be a valid date",
  })
  .transform((value) => new Date(value))
  .refine(
    (date) => {
      const startOfToday = new Date();
      startOfToday.setHours(0, 0, 0, 0);
      return date.getTime() >= startOfToday.getTime();
    },
    { message: "workDate cannot be in the past" }
  );

const locationField = z
  .string({ required_error: "location is required" })
  .trim()
  .min(5, "location must be at least 5 characters")
  .max(500, "location must be at most 500 characters");

const wageField = z
  .number({ required_error: "wage is required", invalid_type_error: "wage must be a number" })
  .positive("wage must be greater than 0")
  .max(100000, "wage must be at most 100000");

const messageField = z
  .string()
  .trim()
  .max(500, "message must be at most 500 characters")
  .optional();

export const createWorkRequestSchema = z.object({
  labourId: labourIdField,
  workType: workTypeField,
  workDate: workDateField,
  location: locationField,
  wage: wageField,
  message: messageField,
});

export type CreateWorkRequestInput = z.infer<typeof createWorkRequestSchema>;

// The labour user's response to a PENDING request. Kept as a single
// endpoint with an `action` discriminator (rather than two separate
// accept/reject endpoints) since both share the same ownership + status
// checks in the service layer.
export const respondWorkRequestSchema = z.object({
  action: z.enum(["ACCEPT", "REJECT"], {
    required_error: "action is required",
    invalid_type_error: "action must be either ACCEPT or REJECT",
  }),
});

export type RespondWorkRequestInput = z.infer<typeof respondWorkRequestSchema>;

// Shared list query for both the farmer's "sent" view and the labour
// user's "received" view — which side is being listed is determined by
// the caller's role in the controller, not by this schema.
export const listWorkRequestsQuerySchema = z.object({
  status: z.enum(WORK_REQUEST_STATUSES).optional(),
  page: z.coerce.number().int().positive().optional().default(1),
  limit: z.coerce.number().int().positive().max(50).optional().default(20),
});

export type ListWorkRequestsQuery = z.infer<typeof listWorkRequestsQuerySchema>;
